language: php
dist: trusty

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: hhvm
      env: HHVM=true

install:
  - composer install --no-dev
  - if [[ $HHVM == true ]]; then composer require "phpunit/phpunit:5.7"; fi

script:
  - if [[ $HHVM == true ]]; then ./vendor/bin/phpunit --version .; fi
  - if [[ $HHVM != true ]]; then phpunit --version .; fi