language: php
sudo: required
dist: precise

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3

install:
  - mkdir -p build/logs
  - composer install --no-progress

script: phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml
  
after_success:
  - travis_retry php vendor/bin/php-coveralls
  # or enable logging
  - travis_retry php vendor/bin/php-coveralls -v