language: php
sudo: required
dist: precise

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
 
before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.3' ]]; then composer require squizlabs/php_codesniffer:2.* -n ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '7.3' ]]; then composer install -n ; fi

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.3' ]]; then vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '7.3' ]]; then vendor/bin/phpunit --no-coverage; fi
  
after_success:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.3' ]]; then php vendor/bin/coveralls -v ; fi